export interface IntegrationAction {
  id: string;
  label: string;
  labelTr: string;
  method: string;
  pathTemplate: string;
  bodyTemplate?: Record<string, any>;
  requiredFields: string[];
  fieldLabels: Record<string, string>;
  fieldPlaceholders: Record<string, string>;
  fieldTypes?: Record<string, "text" | "textarea" | "select">;
  fieldOptions?: Record<string, string[]>;
  responseMapping?: Record<string, string>;
}

export interface Integration {
  id: string;
  name: string;
  nameTr: string;
  category: string;
  categoryTr: string;
  icon: string;
  color: string;
  baseUrl: string;
  authType: "bearer" | "basic" | "query_param" | "custom_header";
  authLabel: string;
  authPlaceholder: string;
  authHeaderName?: string;
  authQueryParam?: string;
  docsUrl: string;
  actions: IntegrationAction[];
}

export const integrationCatalog: Integration[] = [
  {
    id: "slack",
    name: "Slack",
    nameTr: "Slack",
    category: "messaging",
    categoryTr: "Mesajlaşma",
    icon: "slack",
    color: "#4A154B",
    baseUrl: "https://slack.com/api",
    authType: "bearer",
    authLabel: "Bot Token",
    authPlaceholder: "xoxb-...",
    docsUrl: "https://api.slack.com/methods",
    actions: [
      {
        id: "send_message",
        label: "Send Message",
        labelTr: "Mesaj Gönder",
        method: "POST",
        pathTemplate: "/chat.postMessage",
        bodyTemplate: { channel: "{{channel}}", text: "{{message}}" },
        requiredFields: ["channel", "message"],
        fieldLabels: { channel: "Kanal", message: "Mesaj" },
        fieldPlaceholders: { channel: "#general", message: "Merhaba!" },
        fieldTypes: { message: "textarea" },
      },
      {
        id: "send_dm",
        label: "Send Direct Message",
        labelTr: "Direkt Mesaj Gönder",
        method: "POST",
        pathTemplate: "/chat.postMessage",
        bodyTemplate: { channel: "{{userId}}", text: "{{message}}" },
        requiredFields: ["userId", "message"],
        fieldLabels: { userId: "Kullanıcı ID", message: "Mesaj" },
        fieldPlaceholders: { userId: "U0123456789", message: "Merhaba!" },
        fieldTypes: { message: "textarea" },
      },
      {
        id: "list_channels",
        label: "List Channels",
        labelTr: "Kanalları Listele",
        method: "GET",
        pathTemplate: "/conversations.list?types=public_channel&limit={{limit}}",
        requiredFields: [],
        fieldLabels: { limit: "Limit" },
        fieldPlaceholders: { limit: "100" },
      },
    ],
  },
  {
    id: "discord",
    name: "Discord",
    nameTr: "Discord",
    category: "messaging",
    categoryTr: "Mesajlaşma",
    icon: "discord",
    color: "#5865F2",
    baseUrl: "https://discord.com/api/v10",
    authType: "bearer",
    authLabel: "Bot Token",
    authPlaceholder: "Bot token...",
    docsUrl: "https://discord.com/developers/docs",
    actions: [
      {
        id: "send_message",
        label: "Send Message",
        labelTr: "Mesaj Gönder",
        method: "POST",
        pathTemplate: "/channels/{{channelId}}/messages",
        bodyTemplate: { content: "{{message}}" },
        requiredFields: ["channelId", "message"],
        fieldLabels: { channelId: "Kanal ID", message: "Mesaj" },
        fieldPlaceholders: { channelId: "123456789", message: "Merhaba!" },
        fieldTypes: { message: "textarea" },
      },
      {
        id: "create_dm",
        label: "Create DM Channel",
        labelTr: "DM Kanalı Oluştur",
        method: "POST",
        pathTemplate: "/users/@me/channels",
        bodyTemplate: { recipient_id: "{{recipientId}}" },
        requiredFields: ["recipientId"],
        fieldLabels: { recipientId: "Alıcı ID" },
        fieldPlaceholders: { recipientId: "User ID" },
      },
    ],
  },
  {
    id: "telegram",
    name: "Telegram",
    nameTr: "Telegram",
    category: "messaging",
    categoryTr: "Mesajlaşma",
    icon: "telegram",
    color: "#0088cc",
    baseUrl: "https://api.telegram.org",
    authType: "custom_header",
    authLabel: "Bot Token",
    authPlaceholder: "123456:ABC-DEF...",
    docsUrl: "https://core.telegram.org/bots/api",
    actions: [
      {
        id: "send_message",
        label: "Send Message",
        labelTr: "Mesaj Gönder",
        method: "POST",
        pathTemplate: "/bot{{apiKey}}/sendMessage",
        bodyTemplate: { chat_id: "{{chatId}}", text: "{{message}}", parse_mode: "{{parseMode}}" },
        requiredFields: ["chatId", "message"],
        fieldLabels: { chatId: "Chat ID", message: "Mesaj", parseMode: "Format" },
        fieldPlaceholders: { chatId: "-100123456789", message: "Merhaba!", parseMode: "HTML" },
        fieldTypes: { message: "textarea" },
      },
      {
        id: "send_photo",
        label: "Send Photo",
        labelTr: "Fotoğraf Gönder",
        method: "POST",
        pathTemplate: "/bot{{apiKey}}/sendPhoto",
        bodyTemplate: { chat_id: "{{chatId}}", photo: "{{photoUrl}}", caption: "{{caption}}" },
        requiredFields: ["chatId", "photoUrl"],
        fieldLabels: { chatId: "Chat ID", photoUrl: "Fotoğraf URL", caption: "Açıklama" },
        fieldPlaceholders: { chatId: "-100123456789", photoUrl: "https://...", caption: "Opsiyonel" },
      },
    ],
  },
  {
    id: "microsoft_teams",
    name: "Microsoft Teams",
    nameTr: "Microsoft Teams",
    category: "messaging",
    categoryTr: "Mesajlaşma",
    icon: "teams",
    color: "#6264A7",
    baseUrl: "https://graph.microsoft.com/v1.0",
    authType: "bearer",
    authLabel: "Access Token",
    authPlaceholder: "Bearer token...",
    docsUrl: "https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview",
    actions: [
      {
        id: "send_message",
        label: "Send Channel Message",
        labelTr: "Kanal Mesajı Gönder",
        method: "POST",
        pathTemplate: "/teams/{{teamId}}/channels/{{channelId}}/messages",
        bodyTemplate: { body: { content: "{{message}}" } },
        requiredFields: ["teamId", "channelId", "message"],
        fieldLabels: { teamId: "Team ID", channelId: "Kanal ID", message: "Mesaj" },
        fieldPlaceholders: { teamId: "team-id", channelId: "channel-id", message: "Merhaba!" },
        fieldTypes: { message: "textarea" },
      },
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    nameTr: "HubSpot",
    category: "crm",
    categoryTr: "CRM & Satış",
    icon: "hubspot",
    color: "#FF7A59",
    baseUrl: "https://api.hubapi.com",
    authType: "bearer",
    authLabel: "Private App Token",
    authPlaceholder: "pat-...",
    docsUrl: "https://developers.hubspot.com/docs/api",
    actions: [
      {
        id: "create_contact",
        label: "Create Contact",
        labelTr: "Kişi Oluştur",
        method: "POST",
        pathTemplate: "/crm/v3/objects/contacts",
        bodyTemplate: { properties: { email: "{{email}}", firstname: "{{firstName}}", lastname: "{{lastName}}", phone: "{{phone}}" } },
        requiredFields: ["email"],
        fieldLabels: { email: "E-posta", firstName: "Ad", lastName: "Soyad", phone: "Telefon" },
        fieldPlaceholders: { email: "ornek@email.com", firstName: "Ali", lastName: "Yılmaz", phone: "+905551234567" },
      },
      {
        id: "create_deal",
        label: "Create Deal",
        labelTr: "Fırsat Oluştur",
        method: "POST",
        pathTemplate: "/crm/v3/objects/deals",
        bodyTemplate: { properties: { dealname: "{{dealName}}", amount: "{{amount}}", pipeline: "{{pipeline}}", dealstage: "{{stage}}" } },
        requiredFields: ["dealName"],
        fieldLabels: { dealName: "Fırsat Adı", amount: "Tutar", pipeline: "Pipeline", stage: "Aşama" },
        fieldPlaceholders: { dealName: "Yeni Satış", amount: "10000", pipeline: "default", stage: "appointmentscheduled" },
      },
      {
        id: "search_contacts",
        label: "Search Contacts",
        labelTr: "Kişi Ara",
        method: "POST",
        pathTemplate: "/crm/v3/objects/contacts/search",
        bodyTemplate: { filterGroups: [{ filters: [{ propertyName: "{{property}}", operator: "{{operator}}", value: "{{value}}" }] }] },
        requiredFields: ["property", "value"],
        fieldLabels: { property: "Alan", operator: "Operatör", value: "Değer" },
        fieldPlaceholders: { property: "email", operator: "EQ", value: "ornek@email.com" },
      },
    ],
  },
  {
    id: "salesforce",
    name: "Salesforce",
    nameTr: "Salesforce",
    category: "crm",
    categoryTr: "CRM & Satış",
    icon: "salesforce",
    color: "#00A1E0",
    baseUrl: "https://{{instance}}.salesforce.com/services/data/v58.0",
    authType: "bearer",
    authLabel: "Access Token",
    authPlaceholder: "Bearer token...",
    docsUrl: "https://developer.salesforce.com/docs/apis",
    actions: [
      {
        id: "create_lead",
        label: "Create Lead",
        labelTr: "Lead Oluştur",
        method: "POST",
        pathTemplate: "/sobjects/Lead",
        bodyTemplate: { FirstName: "{{firstName}}", LastName: "{{lastName}}", Email: "{{email}}", Company: "{{company}}" },
        requiredFields: ["lastName", "company"],
        fieldLabels: { firstName: "Ad", lastName: "Soyad", email: "E-posta", company: "Şirket" },
        fieldPlaceholders: { firstName: "Ali", lastName: "Yılmaz", email: "ali@firma.com", company: "Firma A.Ş." },
      },
      {
        id: "create_opportunity",
        label: "Create Opportunity",
        labelTr: "Fırsat Oluştur",
        method: "POST",
        pathTemplate: "/sobjects/Opportunity",
        bodyTemplate: { Name: "{{name}}", Amount: "{{amount}}", StageName: "{{stage}}", CloseDate: "{{closeDate}}" },
        requiredFields: ["name", "stage", "closeDate"],
        fieldLabels: { name: "Fırsat Adı", amount: "Tutar", stage: "Aşama", closeDate: "Kapanış Tarihi" },
        fieldPlaceholders: { name: "Yeni Fırsat", amount: "50000", stage: "Prospecting", closeDate: "2026-12-31" },
      },
    ],
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    nameTr: "Pipedrive",
    category: "crm",
    categoryTr: "CRM & Satış",
    icon: "pipedrive",
    color: "#017737",
    baseUrl: "https://api.pipedrive.com/v1",
    authType: "query_param",
    authLabel: "API Token",
    authPlaceholder: "API token...",
    authQueryParam: "api_token",
    docsUrl: "https://developers.pipedrive.com/docs/api/v1",
    actions: [
      {
        id: "create_deal",
        label: "Create Deal",
        labelTr: "Anlaşma Oluştur",
        method: "POST",
        pathTemplate: "/deals",
        bodyTemplate: { title: "{{title}}", value: "{{value}}", currency: "{{currency}}" },
        requiredFields: ["title"],
        fieldLabels: { title: "Başlık", value: "Değer", currency: "Para Birimi" },
        fieldPlaceholders: { title: "Yeni Anlaşma", value: "10000", currency: "TRY" },
      },
      {
        id: "create_person",
        label: "Create Person",
        labelTr: "Kişi Oluştur",
        method: "POST",
        pathTemplate: "/persons",
        bodyTemplate: { name: "{{name}}", email: ["{{email}}"], phone: ["{{phone}}"] },
        requiredFields: ["name"],
        fieldLabels: { name: "Ad Soyad", email: "E-posta", phone: "Telefon" },
        fieldPlaceholders: { name: "Ali Yılmaz", email: "ali@firma.com", phone: "+905551234567" },
      },
    ],
  },
  {
    id: "zoho_crm",
    name: "Zoho CRM",
    nameTr: "Zoho CRM",
    category: "crm",
    categoryTr: "CRM & Satış",
    icon: "zoho",
    color: "#C8202B",
    baseUrl: "https://www.zohoapis.com/crm/v3",
    authType: "bearer",
    authLabel: "OAuth Token",
    authPlaceholder: "Zoho OAuth token...",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/v3/",
    actions: [
      {
        id: "create_lead",
        label: "Create Lead",
        labelTr: "Lead Oluştur",
        method: "POST",
        pathTemplate: "/Leads",
        bodyTemplate: { data: [{ First_Name: "{{firstName}}", Last_Name: "{{lastName}}", Email: "{{email}}", Company: "{{company}}" }] },
        requiredFields: ["lastName"],
        fieldLabels: { firstName: "Ad", lastName: "Soyad", email: "E-posta", company: "Şirket" },
        fieldPlaceholders: { firstName: "Ali", lastName: "Yılmaz", email: "ali@firma.com", company: "Firma" },
      },
    ],
  },
  {
    id: "trello",
    name: "Trello",
    nameTr: "Trello",
    category: "project",
    categoryTr: "Proje Yönetimi",
    icon: "trello",
    color: "#0052CC",
    baseUrl: "https://api.trello.com/1",
    authType: "query_param",
    authLabel: "API Key + Token",
    authPlaceholder: "key=xxx&token=yyy",
    authQueryParam: "key",
    docsUrl: "https://developer.atlassian.com/cloud/trello/rest/",
    actions: [
      {
        id: "create_card",
        label: "Create Card",
        labelTr: "Kart Oluştur",
        method: "POST",
        pathTemplate: "/cards",
        bodyTemplate: { name: "{{name}}", desc: "{{description}}", idList: "{{listId}}" },
        requiredFields: ["name", "listId"],
        fieldLabels: { name: "Kart Adı", description: "Açıklama", listId: "Liste ID" },
        fieldPlaceholders: { name: "Yeni görev", description: "Detaylar...", listId: "list-id" },
        fieldTypes: { description: "textarea" },
      },
      {
        id: "update_card",
        label: "Update Card",
        labelTr: "Kart Güncelle",
        method: "PUT",
        pathTemplate: "/cards/{{cardId}}",
        bodyTemplate: { name: "{{name}}", desc: "{{description}}", closed: "{{closed}}" },
        requiredFields: ["cardId"],
        fieldLabels: { cardId: "Kart ID", name: "Yeni Ad", description: "Yeni Açıklama", closed: "Kapatılsın mı" },
        fieldPlaceholders: { cardId: "card-id", name: "Güncel ad", description: "Güncel açıklama", closed: "false" },
      },
    ],
  },
  {
    id: "asana",
    name: "Asana",
    nameTr: "Asana",
    category: "project",
    categoryTr: "Proje Yönetimi",
    icon: "asana",
    color: "#F06A6A",
    baseUrl: "https://app.asana.com/api/1.0",
    authType: "bearer",
    authLabel: "Personal Access Token",
    authPlaceholder: "0/abc123...",
    docsUrl: "https://developers.asana.com/docs",
    actions: [
      {
        id: "create_task",
        label: "Create Task",
        labelTr: "Görev Oluştur",
        method: "POST",
        pathTemplate: "/tasks",
        bodyTemplate: { data: { name: "{{name}}", notes: "{{notes}}", projects: ["{{projectId}}"], assignee: "{{assignee}}" } },
        requiredFields: ["name", "projectId"],
        fieldLabels: { name: "Görev Adı", notes: "Notlar", projectId: "Proje ID", assignee: "Atanan" },
        fieldPlaceholders: { name: "Yeni görev", notes: "Detaylar...", projectId: "project-id", assignee: "me" },
        fieldTypes: { notes: "textarea" },
      },
    ],
  },
  {
    id: "jira",
    name: "Jira",
    nameTr: "Jira",
    category: "project",
    categoryTr: "Proje Yönetimi",
    icon: "jira",
    color: "#0052CC",
    baseUrl: "https://{{domain}}.atlassian.net/rest/api/3",
    authType: "basic",
    authLabel: "E-posta:API Token",
    authPlaceholder: "email@domain.com:token",
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/",
    actions: [
      {
        id: "create_issue",
        label: "Create Issue",
        labelTr: "Issue Oluştur",
        method: "POST",
        pathTemplate: "/issue",
        bodyTemplate: { fields: { project: { key: "{{projectKey}}" }, summary: "{{summary}}", description: { type: "doc", version: 1, content: [{ type: "paragraph", content: [{ type: "text", text: "{{description}}" }] }] }, issuetype: { name: "{{issueType}}" } } },
        requiredFields: ["projectKey", "summary", "issueType"],
        fieldLabels: { projectKey: "Proje Kodu", summary: "Özet", description: "Açıklama", issueType: "Tür" },
        fieldPlaceholders: { projectKey: "PROJ", summary: "Bug fix", description: "Detaylar...", issueType: "Task" },
      },
    ],
  },
  {
    id: "notion",
    name: "Notion",
    nameTr: "Notion",
    category: "project",
    categoryTr: "Proje Yönetimi",
    icon: "notion",
    color: "#000000",
    baseUrl: "https://api.notion.com/v1",
    authType: "bearer",
    authLabel: "Integration Token",
    authPlaceholder: "secret_...",
    docsUrl: "https://developers.notion.com/",
    actions: [
      {
        id: "create_page",
        label: "Create Page",
        labelTr: "Sayfa Oluştur",
        method: "POST",
        pathTemplate: "/pages",
        bodyTemplate: { parent: { database_id: "{{databaseId}}" }, properties: { Name: { title: [{ text: { content: "{{title}}" } }] } } },
        requiredFields: ["databaseId", "title"],
        fieldLabels: { databaseId: "Veritabanı ID", title: "Başlık" },
        fieldPlaceholders: { databaseId: "database-id", title: "Yeni sayfa" },
      },
      {
        id: "query_database",
        label: "Query Database",
        labelTr: "Veritabanı Sorgula",
        method: "POST",
        pathTemplate: "/databases/{{databaseId}}/query",
        bodyTemplate: {},
        requiredFields: ["databaseId"],
        fieldLabels: { databaseId: "Veritabanı ID" },
        fieldPlaceholders: { databaseId: "database-id" },
      },
    ],
  },
  {
    id: "linear",
    name: "Linear",
    nameTr: "Linear",
    category: "project",
    categoryTr: "Proje Yönetimi",
    icon: "linear",
    color: "#5E6AD2",
    baseUrl: "https://api.linear.app",
    authType: "bearer",
    authLabel: "API Key",
    authPlaceholder: "lin_api_...",
    docsUrl: "https://developers.linear.app/docs",
    actions: [
      {
        id: "create_issue",
        label: "Create Issue",
        labelTr: "Issue Oluştur",
        method: "POST",
        pathTemplate: "/graphql",
        bodyTemplate: { query: "mutation { issueCreate(input: { title: \"{{title}}\", description: \"{{description}}\", teamId: \"{{teamId}}\" }) { success issue { id identifier title } } }" },
        requiredFields: ["title", "teamId"],
        fieldLabels: { title: "Başlık", description: "Açıklama", teamId: "Takım ID" },
        fieldPlaceholders: { title: "Bug fix", description: "Detaylar...", teamId: "team-id" },
      },
    ],
  },
  {
    id: "google_sheets",
    name: "Google Sheets",
    nameTr: "Google Sheets",
    category: "data",
    categoryTr: "Tablo & Veri",
    icon: "sheets",
    color: "#34A853",
    baseUrl: "https://sheets.googleapis.com/v4/spreadsheets",
    authType: "bearer",
    authLabel: "OAuth Token",
    authPlaceholder: "Google OAuth token...",
    docsUrl: "https://developers.google.com/sheets/api/reference/rest",
    actions: [
      {
        id: "append_row",
        label: "Append Row",
        labelTr: "Satır Ekle",
        method: "POST",
        pathTemplate: "/{{spreadsheetId}}/values/{{range}}:append?valueInputOption=USER_ENTERED",
        bodyTemplate: { values: [["{{col1}}", "{{col2}}", "{{col3}}", "{{col4}}"]] },
        requiredFields: ["spreadsheetId", "range", "col1"],
        fieldLabels: { spreadsheetId: "Spreadsheet ID", range: "Aralık", col1: "Sütun 1", col2: "Sütun 2", col3: "Sütun 3", col4: "Sütun 4" },
        fieldPlaceholders: { spreadsheetId: "spreadsheet-id", range: "Sheet1!A:D", col1: "Değer 1", col2: "Değer 2", col3: "Değer 3", col4: "Değer 4" },
      },
      {
        id: "get_values",
        label: "Get Values",
        labelTr: "Değerleri Oku",
        method: "GET",
        pathTemplate: "/{{spreadsheetId}}/values/{{range}}",
        requiredFields: ["spreadsheetId", "range"],
        fieldLabels: { spreadsheetId: "Spreadsheet ID", range: "Aralık" },
        fieldPlaceholders: { spreadsheetId: "spreadsheet-id", range: "Sheet1!A1:D10" },
      },
    ],
  },
  {
    id: "airtable",
    name: "Airtable",
    nameTr: "Airtable",
    category: "data",
    categoryTr: "Tablo & Veri",
    icon: "airtable",
    color: "#18BFFF",
    baseUrl: "https://api.airtable.com/v0",
    authType: "bearer",
    authLabel: "Personal Access Token",
    authPlaceholder: "pat...",
    docsUrl: "https://airtable.com/developers/web/api",
    actions: [
      {
        id: "create_record",
        label: "Create Record",
        labelTr: "Kayıt Oluştur",
        method: "POST",
        pathTemplate: "/{{baseId}}/{{tableName}}",
        bodyTemplate: { fields: { "{{field1Name}}": "{{field1Value}}", "{{field2Name}}": "{{field2Value}}" } },
        requiredFields: ["baseId", "tableName", "field1Name", "field1Value"],
        fieldLabels: { baseId: "Base ID", tableName: "Tablo Adı", field1Name: "Alan 1 Adı", field1Value: "Alan 1 Değeri", field2Name: "Alan 2 Adı", field2Value: "Alan 2 Değeri" },
        fieldPlaceholders: { baseId: "appXXX", tableName: "Tasks", field1Name: "Name", field1Value: "Değer", field2Name: "Status", field2Value: "Active" },
      },
      {
        id: "list_records",
        label: "List Records",
        labelTr: "Kayıtları Listele",
        method: "GET",
        pathTemplate: "/{{baseId}}/{{tableName}}?maxRecords={{maxRecords}}",
        requiredFields: ["baseId", "tableName"],
        fieldLabels: { baseId: "Base ID", tableName: "Tablo Adı", maxRecords: "Maks Kayıt" },
        fieldPlaceholders: { baseId: "appXXX", tableName: "Tasks", maxRecords: "100" },
      },
    ],
  },
  {
    id: "trendyol",
    name: "Trendyol",
    nameTr: "Trendyol",
    category: "ecommerce",
    categoryTr: "E-Ticaret",
    icon: "trendyol",
    color: "#F27A1A",
    baseUrl: "https://api.trendyol.com/sapigw",
    authType: "basic",
    authLabel: "API Key:API Secret",
    authPlaceholder: "apiKey:apiSecret",
    docsUrl: "https://developers.trendyol.com/",
    actions: [
      {
        id: "get_orders",
        label: "Get Orders",
        labelTr: "Siparişleri Getir",
        method: "GET",
        pathTemplate: "/suppliers/{{supplierId}}/orders?status={{status}}&size={{size}}",
        requiredFields: ["supplierId"],
        fieldLabels: { supplierId: "Satıcı ID", status: "Durum", size: "Adet" },
        fieldPlaceholders: { supplierId: "supplier-id", status: "Created", size: "50" },
      },
      {
        id: "update_stock",
        label: "Update Stock",
        labelTr: "Stok Güncelle",
        method: "POST",
        pathTemplate: "/suppliers/{{supplierId}}/products/price-and-inventory",
        bodyTemplate: { items: [{ barcode: "{{barcode}}", quantity: "{{quantity}}" }] },
        requiredFields: ["supplierId", "barcode", "quantity"],
        fieldLabels: { supplierId: "Satıcı ID", barcode: "Barkod", quantity: "Miktar" },
        fieldPlaceholders: { supplierId: "supplier-id", barcode: "8680000000001", quantity: "100" },
      },
    ],
  },
  {
    id: "shopify",
    name: "Shopify",
    nameTr: "Shopify",
    category: "ecommerce",
    categoryTr: "E-Ticaret",
    icon: "shopify",
    color: "#96BF48",
    baseUrl: "https://{{shop}}.myshopify.com/admin/api/2024-01",
    authType: "custom_header",
    authLabel: "Access Token",
    authPlaceholder: "shpat_...",
    authHeaderName: "X-Shopify-Access-Token",
    docsUrl: "https://shopify.dev/docs/api",
    actions: [
      {
        id: "create_product",
        label: "Create Product",
        labelTr: "Ürün Oluştur",
        method: "POST",
        pathTemplate: "/products.json",
        bodyTemplate: { product: { title: "{{title}}", body_html: "{{description}}", vendor: "{{vendor}}", product_type: "{{productType}}" } },
        requiredFields: ["title"],
        fieldLabels: { title: "Ürün Adı", description: "Açıklama", vendor: "Marka", productType: "Ürün Tipi" },
        fieldPlaceholders: { title: "Yeni Ürün", description: "Ürün açıklaması...", vendor: "Marka", productType: "Giyim" },
      },
      {
        id: "get_orders",
        label: "Get Orders",
        labelTr: "Siparişleri Getir",
        method: "GET",
        pathTemplate: "/orders.json?status={{status}}&limit={{limit}}",
        requiredFields: [],
        fieldLabels: { status: "Durum", limit: "Limit" },
        fieldPlaceholders: { status: "any", limit: "50" },
      },
    ],
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    nameTr: "WooCommerce",
    category: "ecommerce",
    categoryTr: "E-Ticaret",
    icon: "woocommerce",
    color: "#96588A",
    baseUrl: "https://{{domain}}/wp-json/wc/v3",
    authType: "basic",
    authLabel: "Consumer Key:Secret",
    authPlaceholder: "ck_xxx:cs_yyy",
    docsUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    actions: [
      {
        id: "create_order",
        label: "Create Order",
        labelTr: "Sipariş Oluştur",
        method: "POST",
        pathTemplate: "/orders",
        bodyTemplate: { payment_method: "{{paymentMethod}}", billing: { first_name: "{{firstName}}", last_name: "{{lastName}}", email: "{{email}}" } },
        requiredFields: ["firstName", "lastName", "email"],
        fieldLabels: { paymentMethod: "Ödeme Yöntemi", firstName: "Ad", lastName: "Soyad", email: "E-posta" },
        fieldPlaceholders: { paymentMethod: "cod", firstName: "Ali", lastName: "Yılmaz", email: "ali@firma.com" },
      },
    ],
  },
  {
    id: "google_drive",
    name: "Google Drive",
    nameTr: "Google Drive",
    category: "storage",
    categoryTr: "Dosya & Depolama",
    icon: "drive",
    color: "#4285F4",
    baseUrl: "https://www.googleapis.com/drive/v3",
    authType: "bearer",
    authLabel: "OAuth Token",
    authPlaceholder: "Google OAuth token...",
    docsUrl: "https://developers.google.com/drive/api/reference/rest/v3",
    actions: [
      {
        id: "list_files",
        label: "List Files",
        labelTr: "Dosyaları Listele",
        method: "GET",
        pathTemplate: "/files?q={{query}}&pageSize={{pageSize}}",
        requiredFields: [],
        fieldLabels: { query: "Arama Sorgusu", pageSize: "Sayfa Boyutu" },
        fieldPlaceholders: { query: "name contains 'rapor'", pageSize: "10" },
      },
      {
        id: "create_folder",
        label: "Create Folder",
        labelTr: "Klasör Oluştur",
        method: "POST",
        pathTemplate: "/files",
        bodyTemplate: { name: "{{folderName}}", mimeType: "application/vnd.google-apps.folder", parents: ["{{parentId}}"] },
        requiredFields: ["folderName"],
        fieldLabels: { folderName: "Klasör Adı", parentId: "Üst Klasör ID" },
        fieldPlaceholders: { folderName: "Yeni Klasör", parentId: "root" },
      },
    ],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    nameTr: "Dropbox",
    category: "storage",
    categoryTr: "Dosya & Depolama",
    icon: "dropbox",
    color: "#0061FF",
    baseUrl: "https://api.dropboxapi.com/2",
    authType: "bearer",
    authLabel: "Access Token",
    authPlaceholder: "sl.xxx...",
    docsUrl: "https://www.dropbox.com/developers/documentation",
    actions: [
      {
        id: "list_folder",
        label: "List Folder",
        labelTr: "Klasörü Listele",
        method: "POST",
        pathTemplate: "/files/list_folder",
        bodyTemplate: { path: "{{path}}", recursive: false, limit: 100 },
        requiredFields: ["path"],
        fieldLabels: { path: "Klasör Yolu" },
        fieldPlaceholders: { path: "/Documents" },
      },
      {
        id: "create_folder",
        label: "Create Folder",
        labelTr: "Klasör Oluştur",
        method: "POST",
        pathTemplate: "/files/create_folder_v2",
        bodyTemplate: { path: "{{path}}", autorename: false },
        requiredFields: ["path"],
        fieldLabels: { path: "Klasör Yolu" },
        fieldPlaceholders: { path: "/NewFolder" },
      },
    ],
  },
  {
    id: "github",
    name: "GitHub",
    nameTr: "GitHub",
    category: "developer",
    categoryTr: "Geliştirici",
    icon: "github",
    color: "#24292F",
    baseUrl: "https://api.github.com",
    authType: "bearer",
    authLabel: "Personal Access Token",
    authPlaceholder: "ghp_...",
    docsUrl: "https://docs.github.com/en/rest",
    actions: [
      {
        id: "create_issue",
        label: "Create Issue",
        labelTr: "Issue Oluştur",
        method: "POST",
        pathTemplate: "/repos/{{owner}}/{{repo}}/issues",
        bodyTemplate: { title: "{{title}}", body: "{{body}}", labels: ["{{label}}"] },
        requiredFields: ["owner", "repo", "title"],
        fieldLabels: { owner: "Sahip", repo: "Repo", title: "Başlık", body: "İçerik", label: "Etiket" },
        fieldPlaceholders: { owner: "username", repo: "my-repo", title: "Bug report", body: "Detaylar...", label: "bug" },
        fieldTypes: { body: "textarea" },
      },
      {
        id: "create_repo",
        label: "Create Repository",
        labelTr: "Repo Oluştur",
        method: "POST",
        pathTemplate: "/user/repos",
        bodyTemplate: { name: "{{name}}", description: "{{description}}", private: true },
        requiredFields: ["name"],
        fieldLabels: { name: "Repo Adı", description: "Açıklama" },
        fieldPlaceholders: { name: "my-project", description: "Proje açıklaması" },
      },
    ],
  },
  {
    id: "twilio",
    name: "Twilio SMS",
    nameTr: "Twilio SMS",
    category: "messaging",
    categoryTr: "Mesajlaşma",
    icon: "twilio",
    color: "#F22F46",
    baseUrl: "https://api.twilio.com/2010-04-01",
    authType: "basic",
    authLabel: "Account SID:Auth Token",
    authPlaceholder: "ACXXX:auth_token",
    docsUrl: "https://www.twilio.com/docs/sms/api",
    actions: [
      {
        id: "send_sms",
        label: "Send SMS",
        labelTr: "SMS Gönder",
        method: "POST",
        pathTemplate: "/Accounts/{{accountSid}}/Messages.json",
        bodyTemplate: { To: "{{to}}", From: "{{from}}", Body: "{{message}}" },
        requiredFields: ["accountSid", "to", "from", "message"],
        fieldLabels: { accountSid: "Account SID", to: "Alıcı", from: "Gönderici", message: "Mesaj" },
        fieldPlaceholders: { accountSid: "ACXXX", to: "+905551234567", from: "+1234567890", message: "Merhaba!" },
      },
    ],
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    nameTr: "Mailchimp",
    category: "marketing",
    categoryTr: "Pazarlama",
    icon: "mailchimp",
    color: "#FFE01B",
    baseUrl: "https://{{dc}}.api.mailchimp.com/3.0",
    authType: "bearer",
    authLabel: "API Key",
    authPlaceholder: "xxx-us1",
    docsUrl: "https://mailchimp.com/developer/marketing/api/",
    actions: [
      {
        id: "add_subscriber",
        label: "Add Subscriber",
        labelTr: "Abone Ekle",
        method: "POST",
        pathTemplate: "/lists/{{listId}}/members",
        bodyTemplate: { email_address: "{{email}}", status: "{{status}}", merge_fields: { FNAME: "{{firstName}}", LNAME: "{{lastName}}" } },
        requiredFields: ["listId", "email", "status"],
        fieldLabels: { listId: "Liste ID", email: "E-posta", status: "Durum", firstName: "Ad", lastName: "Soyad" },
        fieldPlaceholders: { listId: "list-id", email: "ornek@email.com", status: "subscribed", firstName: "Ali", lastName: "Yılmaz" },
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    nameTr: "OpenAI",
    category: "ai",
    categoryTr: "Yapay Zeka",
    icon: "openai",
    color: "#10A37F",
    baseUrl: "https://api.openai.com/v1",
    authType: "bearer",
    authLabel: "API Key",
    authPlaceholder: "sk-...",
    docsUrl: "https://platform.openai.com/docs/api-reference",
    actions: [
      {
        id: "chat_completion",
        label: "Chat Completion",
        labelTr: "AI Yanıt Üret",
        method: "POST",
        pathTemplate: "/chat/completions",
        bodyTemplate: { model: "{{model}}", messages: [{ role: "system", content: "{{systemPrompt}}" }, { role: "user", content: "{{userMessage}}" }], temperature: 0.7 },
        requiredFields: ["userMessage"],
        fieldLabels: { model: "Model", systemPrompt: "Sistem Promptu", userMessage: "Kullanıcı Mesajı" },
        fieldPlaceholders: { model: "gpt-4o-mini", systemPrompt: "Sen yardımcı bir asistansın.", userMessage: "Merhaba, bana yardım eder misin?" },
        fieldTypes: { systemPrompt: "textarea", userMessage: "textarea" },
      },
    ],
  },
  {
    id: "google_calendar",
    name: "Google Calendar",
    nameTr: "Google Takvim",
    category: "productivity",
    categoryTr: "Verimlilik",
    icon: "calendar",
    color: "#4285F4",
    baseUrl: "https://www.googleapis.com/calendar/v3",
    authType: "bearer",
    authLabel: "OAuth Token",
    authPlaceholder: "Google OAuth token...",
    docsUrl: "https://developers.google.com/calendar/api/v3/reference",
    actions: [
      {
        id: "create_event",
        label: "Create Event",
        labelTr: "Etkinlik Oluştur",
        method: "POST",
        pathTemplate: "/calendars/{{calendarId}}/events",
        bodyTemplate: { summary: "{{title}}", description: "{{description}}", start: { dateTime: "{{startTime}}" }, end: { dateTime: "{{endTime}}" } },
        requiredFields: ["calendarId", "title", "startTime", "endTime"],
        fieldLabels: { calendarId: "Takvim ID", title: "Başlık", description: "Açıklama", startTime: "Başlangıç", endTime: "Bitiş" },
        fieldPlaceholders: { calendarId: "primary", title: "Toplantı", description: "Detaylar...", startTime: "2026-04-01T10:00:00+03:00", endTime: "2026-04-01T11:00:00+03:00" },
      },
      {
        id: "list_events",
        label: "List Events",
        labelTr: "Etkinlikleri Listele",
        method: "GET",
        pathTemplate: "/calendars/{{calendarId}}/events?maxResults={{maxResults}}&timeMin={{timeMin}}",
        requiredFields: ["calendarId"],
        fieldLabels: { calendarId: "Takvim ID", maxResults: "Maks Sonuç", timeMin: "Başlangıç Tarihi" },
        fieldPlaceholders: { calendarId: "primary", maxResults: "10", timeMin: "2026-01-01T00:00:00Z" },
      },
    ],
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    nameTr: "SendGrid",
    category: "marketing",
    categoryTr: "Pazarlama",
    icon: "sendgrid",
    color: "#1A82E2",
    baseUrl: "https://api.sendgrid.com/v3",
    authType: "bearer",
    authLabel: "API Key",
    authPlaceholder: "SG.xxx...",
    docsUrl: "https://docs.sendgrid.com/api-reference",
    actions: [
      {
        id: "send_email",
        label: "Send Email",
        labelTr: "E-posta Gönder",
        method: "POST",
        pathTemplate: "/mail/send",
        bodyTemplate: { personalizations: [{ to: [{ email: "{{to}}" }] }], from: { email: "{{from}}" }, subject: "{{subject}}", content: [{ type: "text/html", value: "{{body}}" }] },
        requiredFields: ["to", "from", "subject", "body"],
        fieldLabels: { to: "Alıcı", from: "Gönderici", subject: "Konu", body: "İçerik" },
        fieldPlaceholders: { to: "alici@email.com", from: "sender@domain.com", subject: "Konu", body: "<p>İçerik</p>" },
        fieldTypes: { body: "textarea" },
      },
    ],
  },
  {
    id: "stripe_integration",
    name: "Stripe",
    nameTr: "Stripe",
    category: "finance",
    categoryTr: "Finans",
    icon: "stripe",
    color: "#635BFF",
    baseUrl: "https://api.stripe.com/v1",
    authType: "bearer",
    authLabel: "Secret Key",
    authPlaceholder: "sk_live_...",
    docsUrl: "https://stripe.com/docs/api",
    actions: [
      {
        id: "create_customer",
        label: "Create Customer",
        labelTr: "Müşteri Oluştur",
        method: "POST",
        pathTemplate: "/customers",
        bodyTemplate: { email: "{{email}}", name: "{{name}}", description: "{{description}}" },
        requiredFields: ["email"],
        fieldLabels: { email: "E-posta", name: "Ad Soyad", description: "Açıklama" },
        fieldPlaceholders: { email: "musteri@email.com", name: "Ali Yılmaz", description: "VIP müşteri" },
      },
      {
        id: "create_invoice",
        label: "Create Invoice",
        labelTr: "Fatura Oluştur",
        method: "POST",
        pathTemplate: "/invoices",
        bodyTemplate: { customer: "{{customerId}}", collection_method: "send_invoice", days_until_due: 30 },
        requiredFields: ["customerId"],
        fieldLabels: { customerId: "Müşteri ID" },
        fieldPlaceholders: { customerId: "cus_xxx" },
      },
    ],
  },
  {
    id: "zapier_webhook",
    name: "Zapier Webhook",
    nameTr: "Zapier Webhook",
    category: "automation",
    categoryTr: "Otomasyon",
    icon: "zapier",
    color: "#FF4A00",
    baseUrl: "",
    authType: "bearer",
    authLabel: "Gerekli Değil",
    authPlaceholder: "",
    docsUrl: "https://zapier.com/help/create/code-webhooks/send-webhooks-in-zaps",
    actions: [
      {
        id: "trigger_zap",
        label: "Trigger Zap",
        labelTr: "Zap Tetikle",
        method: "POST",
        pathTemplate: "{{webhookUrl}}",
        bodyTemplate: { data: "{{data}}" },
        requiredFields: ["webhookUrl"],
        fieldLabels: { webhookUrl: "Webhook URL", data: "Veri" },
        fieldPlaceholders: { webhookUrl: "https://hooks.zapier.com/...", data: "{{triggerData}}" },
        fieldTypes: { data: "textarea" },
      },
    ],
  },
  {
    id: "make_webhook",
    name: "Make (Integromat)",
    nameTr: "Make (Integromat)",
    category: "automation",
    categoryTr: "Otomasyon",
    icon: "make",
    color: "#6D00CC",
    baseUrl: "",
    authType: "bearer",
    authLabel: "Gerekli Değil",
    authPlaceholder: "",
    docsUrl: "https://www.make.com/en/help/tools/webhooks",
    actions: [
      {
        id: "trigger_scenario",
        label: "Trigger Scenario",
        labelTr: "Senaryo Tetikle",
        method: "POST",
        pathTemplate: "{{webhookUrl}}",
        bodyTemplate: { data: "{{data}}" },
        requiredFields: ["webhookUrl"],
        fieldLabels: { webhookUrl: "Webhook URL", data: "Veri" },
        fieldPlaceholders: { webhookUrl: "https://hook.eu1.make.com/...", data: "{{triggerData}}" },
        fieldTypes: { data: "textarea" },
      },
    ],
  },
];

export function getIntegrationById(id: string): Integration | undefined {
  return integrationCatalog.find((i) => i.id === id);
}

export function getIntegrationsByCategory(): Record<string, Integration[]> {
  const result: Record<string, Integration[]> = {};
  for (const integration of integrationCatalog) {
    if (!result[integration.category]) result[integration.category] = [];
    result[integration.category].push(integration);
  }
  return result;
}

export function getCategoryLabels(): Record<string, string> {
  const labels: Record<string, string> = {};
  for (const integration of integrationCatalog) {
    labels[integration.category] = integration.categoryTr;
  }
  return labels;
}

export function getTotalActionCount(): number {
  return integrationCatalog.reduce((sum, i) => sum + i.actions.length, 0);
}

export function getTotalIntegrationCount(): number {
  return integrationCatalog.length;
}
