import { storage } from "./storage";
import type { InsertBossNotification } from "@shared/schema";

export async function notifyBoss(params: {
  userId: number;
  type: string;
  teamMemberName: string;
  summary: string;
  details?: Record<string, any>;
}): Promise<void> {
  try {
    const notification: InsertBossNotification = {
      userId: params.userId,
      type: params.type,
      teamMemberName: params.teamMemberName,
      summary: params.summary,
      details: params.details || null,
      bossResponse: null,
      adminNotified: false,
    };

    const created = await storage.createBossNotification(notification);

    const user = await storage.getUserById(params.userId);
    if (user?.gmailAddress && user?.gmailAppPassword) {
      const { setActiveUserGmail, sendViaGmail } = await import("./gmailService");
      setActiveUserGmail({ gmailAddress: user.gmailAddress, gmailAppPassword: user.gmailAppPassword });

      const emailBody = `Boss AI Notification\n\nType: ${params.type}\nTeam Member: ${params.teamMemberName}\n\nSummary:\n${params.summary}\n\n${params.details ? `Details:\n${JSON.stringify(params.details, null, 2)}` : ""}\n\n---\nThis notification was generated by Boss AI on RentAI 24.`;

      await sendViaGmail({
        to: user.email,
        subject: `[Boss AI] ${params.type}: ${params.teamMemberName} - ${params.summary.substring(0, 50)}`,
        body: emailBody,
      });

      await storage.createBossNotification({
        ...notification,
        adminNotified: true,
        bossResponse: `Email notification sent to ${user.email}`,
      });
    }

    console.log(`[BossAI] Notification created for user ${params.userId}: ${params.type} - ${params.teamMemberName}`);
  } catch (error) {
    console.error("[BossAI] Failed to create notification:", error);
  }
}

export async function triggerEmailReplyNotification(params: {
  userId: number;
  agentType: string;
  teamMemberName: string;
  recipientEmail: string;
  subject: string;
  replySnippet: string;
}): Promise<void> {
  await notifyBoss({
    userId: params.userId,
    type: "email_reply",
    teamMemberName: params.teamMemberName,
    summary: `${params.agentType} sent an email reply to ${params.recipientEmail} regarding "${params.subject}"`,
    details: {
      agentType: params.agentType,
      recipient: params.recipientEmail,
      subject: params.subject,
      replySnippet: params.replySnippet.substring(0, 200),
    },
  });
}

export async function triggerTaskCompleteNotification(params: {
  userId: number;
  agentType: string;
  teamMemberName: string;
  taskDescription: string;
  result: string;
}): Promise<void> {
  await notifyBoss({
    userId: params.userId,
    type: "task_complete",
    teamMemberName: params.teamMemberName,
    summary: `${params.agentType} completed task: ${params.taskDescription}`,
    details: {
      agentType: params.agentType,
      task: params.taskDescription,
      result: params.result.substring(0, 500),
    },
  });
}
